In [ ]:
# ¿Por qué usar Numpy?

* Calculo científico
* Estadistica
* Optimizado en memoria cache 


In [4]:
#Importando librería
import numpy
import numpy as np

In [7]:
#Arrays -> clase ndarray
array = np.array([[1,2,3],[4,5,6]])
array?
type(array)

numpy.ndarray

Type:        ndarray
String form:
[[1 2 3]
 [4 5 6]]
Length:      2
File:        ~/.local/lib/python3.9/site-packages/numpy/__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object t

In [19]:
#Propiedades
print("Dimensiones del array : ", array.shape)
print("Tipo de elementos : \n", array.dtype)
print("Número de bytes necesarios : ", array.nbytes)
print("Número de dimensiones : ", array.ndim)
print("Total de elementos en el array : ", array.size)
print("Propiedades de los objetos ndarray :")
np.ndarray?

Dimensiones del array :  (2, 3)
Tipo de elementos : 
 int64
Número de bytes necesarios :  48
Número de dimensiones :  2
Total de elementos en el array :  6
Propiedades de los objetos ndarray :


Init signature: np.ndarray(self, /, *args, **kwargs)
Docstring:     
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer int

In [24]:
#Crear un array con un tipo de datos concreto
#tipos enteros int8, int16, int32, int64
#tipos enteros sin signo uint8,  uint16, uint32, uint64
#tipos reales float16, float32, float64

datos = np.array([1,2,3], dtype=np.int)
print(datos)
datos1 = np.array([1,3,4], dtype=np.float)
print(datos1)
datos2 = np.array([1,2,3], dtype=np.complex)
print(datos2)

[1 2 3]
[1. 3. 4.]
[1.+0.j 2.+0.j 3.+0.j]


/tmp/ipykernel_18039/1614338763.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  datos = np.array([1,2,3], dtype=np.int)
/tmp/ipykernel_18039/1614338763.py:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  datos1 = np.ar

In [45]:
# crea un array copia
array_normal = np.array([1,2,3,4,5], dtype=np.int64)
print(array_normal)
array_copia = np.array(array_normal, dtype=np.float32)
print(array_copia)

#Crear un array apartir de un objeto iterable
array = np.array(range(10,20))
print(array)

#Crear array con valores contantes
# (filas, columnas)
array1 = np.zeros((3,4), dtype=np.int64)
print(array1)
array2 = np.ones(7, dtype=np.int)
print(array2)
#Crear array con valores distintos a ceros y unos
#Especificamos el número de elementos y el valor que van a tomar
array3 = np.full( (2,3), 1.1, dtype=np.float32)
print(array3)
# Rellenar un array  previamente creado con un valor constante
array_copia.fill(9.9)
print(array_copia)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[10 11 12 13 14 15 16 17 18 19]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[1 1 1 1 1 1 1]
[[1.1 1.1 1.1]
 [1.1 1.1 1.1]]
[9.9 9.9 9.9 9.9 9.9]


/tmp/ipykernel_18039/1994253614.py:15: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  array2 = np.ones(7, dtype=np.int)


In [52]:
#Creación de un array como una secuencia de valores
# inicio y final (sin incluirlo) y el incremento que se realiza 
array = np.arange(start= 1, stop=5, step=0.5)
print(array)

#Rango de 1 a 10 con ambos incluidos y le dices cuantos elementos tiene
array1 = np.linspace(1, 10, 7)
print(array1)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]


In [64]:
#Creación de numeros seudo aleatorios

#Generar un número
array = np.random.rand()
print(array)

#Generar un array bidimensional de numeros

array1 = np.random.rand(3,4)
print(array1)

#Agregar una semilla para poder repetir la secuencia una y otra vez

np.random.seed(3)
print("Generando el mismo valor")
print(np.random.rand(4))


0.8929469543476547
[[0.89629309 0.12558531 0.20724288 0.0514672 ]
 [0.44080984 0.02987621 0.45683322 0.64914405]
 [0.27848728 0.6762549  0.59086282 0.02398188]]
Generando el mismo valor
[0.5507979  0.70814782 0.29090474 0.51082761]


In [74]:
#crear valores aleatorios entre unos valores determinados
array = np.random.randint(low=10, high=50, size = (3,2))
print(array)





[[38 10]
 [10 28]
 [47 17]]


In [88]:
#Guardar un array como .dat o csv
np.savetxt('./array-save.dat', array)
np.savetxt('./array-save.csv', array)
array = np.array(range(0,10))
print(array)
suma_acumulada = np.cumsum(array)
print(suma_acumulada)
np.savetxt('./array-save-name.csv', suma_acumulada, delimiter=',')



[0 1 2 3 4 5 6 7 8 9]
[ 0  1  3  6 10 15 21 28 36 45]


In [85]:
#Carga un array de un .dat o csv
c1 = np.loadtxt('./array-save.dat',dtype=np.int)
print(c1)

#uso de  delimiter=','  usecols=[1]
c2 = np.loadtxt('./array-save.csv', dtype=np.int)
print(c2)

c3 = np.loadtxt('./array-save-columns.csv', dtype=np.int, delimiter=',' , usecols=[0])
print(c3)


[[25 47]
 [30 40]
 [31 24]]
[[25 47]
 [30 40]
 [31 24]]
[1 4 7]


/tmp/ipykernel_18039/1129103868.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  c1 = np.loadtxt('./array-save.dat',dtype=np.int)
/tmp/ipykernel_18039/1129103868.py:2: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point

In [93]:
nuevo = np.genfromtxt('./array-save-columns-name.csv', delimiter=',', names=True)
nuevo['minutos']
nuevo['horas']
nuevo.dtype

dtype([('minutos', '<f8'), ('horas', '<f8'), ('segundos', '<f8')])