# Operaciones vectorizadas

In [3]:
import numpy as np

#Operaciones aritméticas *,-,+,** (se puede hacer con array bidimensional igual)
a = np.array([1,2,3],int)
b = np.array([3,2,1],int)

print(a + b)
print(a * b)

#funciones universales

print(np.sqrt(a))
print(np.maximum(a,b))

#Funciones de agregación

#np.max , np.sum, np.meano(mediana), np.std(desviación tipica)
datos = np.arange(1,10)
print(datos)

print("media ",datos.mean())
print("producto ", datos.prod())



[4 4 4]
[3 4 3]
[1.         1.41421356 1.73205081]
[3 2 3]
[1 2 3 4 5 6 7 8 9]
media  5.0
producto  362880


In [4]:
#si tenemos un matrix podemos sumar en el eje x o eje y
datos = np.arange(1,10)
datos = datos.reshape(3,3)
print(datos)

print(datos.sum())

print("Eje x ",datos.sum(axis = 0))
print("Eje Y", datos.sum(axis = 1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
Eje x  [12 15 18]
Eje Y [ 6 15 24]


In [5]:
#Operaciones con tipo bool

x = np.arange(1,6)
print(x)
y = np.arange(5,11)
print(y)

np.all(x < y)
np.any( x < y)

[1 2 3 4 5]
[ 5  6  7  8  9 10]


ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [8]:
#Operaciones de cojuntos

a = np.array([1,2,4,5,6,7,7])
b = np.array([7,8,9,10,11,11])

#array unico
c = np.unique(a)
print(c)
#Comprobar si los elementos de un array estan en el otro
print(np.in1d(a ,b))
#Crea un nuevo elemento union 
union = np.union1d(a,b)
print(union)
#crea un nuevo elemento intersección
inter = np.intersect1d(a,b)
print(inter)
#crea un nuevo elemento diferencia
diff = np.setdiff1d(a,b)
print(diff)



[1 2 4 5 6 7]
[False False False False False  True  True]
[ 1  2  4  5  6  7  8  9 10 11]
[7]
[1 2 4 5 6]


In [ ]:
# Orden
array = np.array([1,7,5,6,6,5,4,-1,-2])
print(array)
#orden elementos
np.sort(array)

[ 1  7  5  6  6  5  4 -1 -2]


array([-2, -1,  1,  4,  5,  5,  6,  6,  7])