<div id="navegacion" prev="../Ejercicios_Tema_6/uso_numpy.html" next=""></div>

<div class="section-title">Sección 3.7</div>

# Ejercicios 

Los enlaces que te encuentres en esta página, solo funcionan desde el formato html, no desde el notebook una vez descargado.

## Ejercicio 1

El fichero [rotterdam_rainfall.txt](./datos/rotterdam_rainfall.txt) recoge los datos de las precipitaciones diarias de la estación meteorológica de Rotterdam en 2012.

* La primera columna representa la fecha.
* La segunda columna representa la cantidad de precipitaciones expresado en 0.1 mm (-1 si es menor a 0.05 mm).
* El separador de campos es el caracter `, `.

__a)__ Crear un array de `numpy` con los datos del fichero [rotterdam_rainfall.txt](./datos/rotterdam_rainfall.txt). El array ha de llamarse `precipitaciones`.

   * Descarga el fichero  en tu directorio de trabajo.
   * Carga el fichero mediante la función `loadtxt`. Usa el parámetro  `delimiter` con valor `,`. Usa el parámetro `dtype` para indicar que los valores sean de tipo `int`.

In [33]:
# Sol
import numpy as np

#fecha y cantidad de precipitaciones
precipitaciones = np.loadtxt("rotterdam_rainfall.txt", delimiter=',',dtype=int)

#print(precipitaciones)

#conocer el array que tenemos
print(precipitaciones)
print(precipitaciones.size)
print(precipitaciones.shape)
print(precipitaciones.ndim)
print(precipitaciones.dtype)


[[20120101      207]
 [20120102       -1]
 [20120103      144]
 [20120104       36]
 [20120105       84]
 [20120106        8]
 [20120107       30]
 [20120108       -1]
 [20120109        8]
 [20120110        0]
 [20120111       10]
 [20120112        9]
 [20120113        4]
 [20120114       -1]
 [20120115        0]
 [20120116        0]
 [20120117        0]
 [20120118       32]
 [20120119      144]
 [20120120       -1]
 [20120121       35]
 [20120122       19]
 [20120123       16]
 [20120124        5]
 [20120125        5]
 [20120126       33]
 [20120127       -1]
 [20120128       -1]
 [20120129        0]
 [20120130        1]
 [20120131       -1]
 [20120201        0]
 [20120202        0]
 [20120203       27]
 [20120204        0]
 [20120205        0]
 [20120206        0]
 [20120207        0]
 [20120208        0]
 [20120209       -1]
 [20120210        0]
 [20120211        0]
 [20120212        5]
 [20120213       18]
 [20120214       19]
 [20120215       29]
 [20120216        6]
 [20120217   

__b)__ Averigua el número de días donde la cantidad de precipitaciones es mayor a 0.05 mm (valor mayor que -1).
    
* Primero crea un filtro donde la cantidad de precipitaciones (columna 1) sea mayor que  -1.
* Aplica el filtro al array `precipitaciones`. Guarda el resultado en un nuevo array llamado `precip_positivas`.
* Puedes usar la función `len` para calcular el tamaño del array  `precip_positivas`.

In [35]:
# Sol: 324 días 

precip_positivas = [y for x, y in precipitaciones if y > -1]

print(precip_positivas)

len(precip_positivas)


[207, 144, 36, 84, 8, 30, 8, 0, 10, 9, 4, 0, 0, 0, 32, 144, 35, 19, 16, 5, 5, 33, 0, 1, 0, 0, 27, 0, 0, 0, 0, 0, 0, 0, 5, 18, 19, 29, 6, 4, 80, 25, 0, 26, 1, 0, 0, 0, 3, 0, 0, 43, 45, 0, 123, 0, 0, 1, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 0, 10, 3, 30, 65, 23, 13, 0, 6, 35, 8, 32, 15, 12, 1, 38, 30, 25, 66, 4, 119, 1, 102, 113, 0, 1, 66, 124, 54, 2, 0, 15, 106, 21, 0, 3, 0, 51, 0, 0, 0, 0, 0, 0, 0, 0, 35, 0, 72, 5, 101, 157, 1, 69, 17, 7, 21, 186, 16, 0, 0, 96, 32, 130, 0, 0, 112, 71, 0, 132, 0, 0, 0, 37, 4, 0, 0, 1, 40, 107, 6, 69, 3, 126, 67, 43, 81, 104, 212, 1, 48, 72, 1, 0, 0, 0, 0, 0, 83, 1, 36, 97, 14, 37, 51, 36, 6, 130, 8, 118, 1, 0, 0, 0, 0, 20, 3, 2, 0, 0, 0, 6, 0, 0, 0, 19, 47, 182, 24, 16, 89, 139, 0, 0, 0, 0, 0, 0, 0, 0, 1, 4, 30, 0, 8, 0, 8, 50, 17, 14, 5, 27, 70, 148, 78, 44, 6, 10, 0, 19, 12, 49, 107, 130, 141, 0, 0, 0, 7, 115, 166, 143, 14, 29, 18, 100, 35, 4, 8, 0, 0, 1, 3, 1, 119, 105, 45, 16, 15, 103, 46, 105, 4, 2, 1, 42, 36, 4, 5, 0, 0, 

324


__c)__ Calcula el valor medio de la cantidad de precipitación. No tengas en cuenta las precipitaciones con valor -1, por tanto usa el array `precip_positivas` para calcular dicho valor medio.

   * Utiliza la función `mean`.
    


In [36]:
# Sol: 30.700617283950617

np.mean(precip_positivas)


30.700617283950617

__d)__ Calcula el día que ha tenido mayor cantidad de precipitación y la cantidad de precipitación.

   * Utiliza las funciones `argmax` y `max`.

In [49]:
# Sol: Máxima precipitación: 224. 
#      Día de máxima precipitación : 20121222

#Guardamos el mayor indice
#para ello nos vamos a fijar en la columna 2 del array 
indice = np.argmax(precipitaciones[:,1])


print("Maxima precipación :  {}".format(precipitaciones[indice,1]))
print("Día de máxima precipatación : {}".format(precipitaciones[indice,0]))


Maxima precipación :  224
Día de máxima precipatación : 20121222


__e)__ Expresa la cantidad de precipitación en mm. Para ello multiplica la cantidad de precipitación por 10.

   

In [51]:
# Sol: Los primeros valores del resultado son:

#    array([[20120101,     2070],
#           [20120102,      -10],
#           [20120103,     1440],
#           [20120104,      360],
#            ...
#            ...

#actualizar la segunda columna -> machando los valores anterior
precipitaciones[:,1] = precipitaciones[:,1]*10
print(precipitaciones)




[[20120101     2070]
 [20120102      -10]
 [20120103     1440]
 [20120104      360]
 [20120105      840]
 [20120106       80]
 [20120107      300]
 [20120108      -10]
 [20120109       80]
 [20120110        0]
 [20120111      100]
 [20120112       90]
 [20120113       40]
 [20120114      -10]
 [20120115        0]
 [20120116        0]
 [20120117        0]
 [20120118      320]
 [20120119     1440]
 [20120120      -10]
 [20120121      350]
 [20120122      190]
 [20120123      160]
 [20120124       50]
 [20120125       50]
 [20120126      330]
 [20120127      -10]
 [20120128      -10]
 [20120129        0]
 [20120130       10]
 [20120131      -10]
 [20120201        0]
 [20120202        0]
 [20120203      270]
 [20120204        0]
 [20120205        0]
 [20120206        0]
 [20120207        0]
 [20120208        0]
 [20120209      -10]
 [20120210        0]
 [20120211        0]
 [20120212       50]
 [20120213      180]
 [20120214      190]
 [20120215      290]
 [20120216       60]
 [20120217   

## Ejercicio 2

Dos niños están haciendo una colección de cromos. Cada cromo tiene asignado un número entero entre 1 y 200.

* Los cromos que tiene Juan se encuentran en el fichero [juan.txt](./datos/col_juan.txt). La primera columna representa el número asociado al cromo y la segunda columna representa el número de cromos con ese número que tiene Juan.

* Los cromos que tiene Pedro se encuentran en el fichero [pedro.txt](./datos/col_pedro.txt). La primera columna representa el número asociado al cromo y la segunda columna representa el número de cromos con ese número que tiene Pedro.

__a)__ Crear un array de `numpy` con los datos de cada una de las colecciones. Los arrays han de llamarse `juan`y `pedro`.

   * Descarga los ficheros  en tu directorio de trabajo.
   * Carga cada uno de los ficheros mediante la función `loadtxt`. Usa el parámetro  `delimiter` con valor `,`. Usa el parámetro `dtype` para indicar que los valores sean de tipo `int`.

In [52]:
# Sol: 

juan = np.loadtxt("col_juan.txt",delimiter=',',dtype=int)
pedro = np.loadtxt("col_pedro.txt", delimiter=',',dtype=int)


[[  2   4]
 [  5   5]
 [  8  13]
 [ 15  11]
 [ 25   4]
 [ 28  14]
 [ 31  15]
 [ 33  17]
 [ 37   7]
 [ 40   3]
 [ 41   1]
 [ 42   9]
 [ 43   3]
 [ 49   6]
 [ 53   8]
 [ 54  14]
 [ 57  10]
 [ 60  10]
 [ 61   2]
 [ 62  15]
 [ 67   3]
 [ 68   5]
 [ 70  14]
 [ 71  10]
 [ 74   9]
 [ 80  16]
 [ 90   1]
 [ 97  17]
 [105  15]
 [108  18]
 [110  15]
 [111   2]
 [112   6]
 [116   9]
 [117   5]
 [123  10]
 [127  10]
 [130  17]
 [132   3]
 [133   4]
 [134   7]
 [135   9]
 [137  14]
 [142   7]
 [143  10]
 [144   3]
 [145  15]
 [148   3]
 [152  11]
 [153   5]
 [157  10]
 [158  12]
 [159   2]
 [160  16]
 [163   5]
 [164   3]
 [166  19]
 [167  17]
 [168   7]
 [170  13]
 [171  15]
 [172  15]
 [178  12]
 [182   2]
 [183   2]
 [192   2]
 [197  14]
 [198   9]]


/tmp/ipykernel_60259/4064831525.py:3: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  juan = np.loadtxt("col_juan.txt",delimiter=',',dtype=int)
/tmp/ipykernel_60259/4064831525.py:4: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On a

__b)__ Calcula el número de cromos diferentes que tiene cada niño. 

In [56]:
# SOl: 
# juan tiene 68 cromos
# pedro tiene 124 cromos

print("juan tiene {} cromo".format(len(juan)))
print("pedro tiene {} cromos".format(len(pedro)))



juan tiene 68 cromo
pedro tiene 124 cromos


__c)__ Calcula el número de cromos totales que tiene cada niño (contando los cromos repetidos). 

In [64]:
# SOl: 
# pedro tiene 1326 cromos 
# juan tiene 619 cromos

sum = np.sum(juan[:,1])

print("pedro tiene {} cromos".format(np.sum(pedro[:,1])))
print("juan tiene {} cromos".format(sum))


pedro tiene 1326 cromos
juan tiene 619 cromos


__d)__ Calcula el número de cromos que aparecen en las dos colecciones. Puedes usar la función `np.intersect1d`.

In [69]:
# Sol
# Hay 44 cromos que aparecen en las dos colecciones

new_array = np.intersect(juan[:,0],pedro[:,0])
#print(new_array)
print(len(new_array))


44


__e)__ Entre los dos niños, ¿forman la colección completa?. Puedes usar la función `np.union1d`.

In [78]:
# Sol: 
# No Forman la colección completa. Entre los dos, solo tienen 148 cromos distintos y la colección tiene 200 cromos

new_array_union = np.union1d(juan[:,0],pedro[:,0])
print(new_array_union)
print(len(new_array_union))




[  2   4   5   6   7   8   9  10  11  13  14  15  18  19  20  22  23  24
  25  26  27  28  29  31  32  33  35  36  37  39  40  41  42  43  44  47
  49  50  51  53  54  56  57  58  59  60  61  62  63  64  65  67  68  70
  71  73  74  77  78  79  80  83  84  85  86  87  88  89  90  93  94  95
  97  98  99 101 102 103 104 105 108 109 110 111 112 115 116 117 118 120
 121 123 126 127 128 130 131 132 133 134 135 136 137 141 142 143 144 145
 147 148 149 150 152 153 156 157 158 159 160 161 162 163 164 165 166 167
 168 169 170 171 172 174 175 177 178 179 182 183 187 188 189 191 192 193
 195 196 197 198]
148


__f)__ ¿Qué números faltan para tener la colección completa?

* Puedes generar un array de todos los cromos de la colección con la función `arange`.
* Usa la función `np.in1d` 

In [95]:
# Sol:
# Listado de los cromos que faltan:
#      [  1,   3,  12,  16,  17,  21,  30,  34,  38,  45,  46,  48,  52,
#        55,  66,  69,  72,  75,  76,  81,  82,  91,  92,  96, 100, 106,
#       107, 113, 114, 119, 122, 124, 125, 129, 138, 139, 140, 146, 151,
#       154, 155, 173, 176, 180, 181, 184, 185, 186, 190, 194, 199, 200]
    


new_array_arange = np.arange(1,201)

#transformamos los verdades en falsos y asi los falsos en verdaderos que son los 
#que queremos mostrar
new_array_in1d = ~np.in1d(new_array_arange, new_array_union)

#print(new_array_arange[new_array_in1d])





[  1   3  12  16  17  21  30  34  38  45  46  48  52  55  66  69  72  75
  76  81  82  91  92  96 100 106 107 113 114 119 122 124 125 129 138 139
 140 146 151 154 155 173 176 180 181 184 185 186 190 194 199 200]


---------------------