In [1]:
#Importa libreria

import numpy as np

# Array de una dimensión

In [14]:

array = np.arange(0,12)
print(array)

#seleccionar el primero y el ultimo
print(array[0],array[-1])

#seleccionar el elemento 2 al 5
print(array[2:6])

#los tres ultimos elemento
print(array[-3:])

#orden inverso
print(array[::-1])
#orden inverso con incremento de 2
print(array[::-2])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
0 11
[2 3 4 5]
[ 9 10 11]
[11 10  9  8  7  6  5  4  3  2  1  0]
[11  9  7  5  3  1]


# Array multidimensionales

In [22]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype='int')
print(array)

#selecciónar la segunda fila
print("Segunda fila",array[1,:])
#seleccionar la segunda columna
print("Segunda columna",array[:,1])

#copiar un array en otro
array_copia = array[2,:]
print(array_copia)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Segunda fila [4 5 6]
Segunda columna [2 5 8]
[7 8 9]


In [24]:
#filtrado
b = np.arange(12)
print(b)

print(b > 7)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[False False False False False False False False  True  True  True  True]


In [36]:
#manipular la forma de un array

#con reshape y ravel se crean vistas
#Cambiar dimensiones una array
array = np.array([[2,4,6],[1,2,3]], dtype='int')
print(array)

print(array.reshape(6))
print(array.reshape(3,2))

#cambiar dimensiones una array a una dimensión
print(array.ravel())


#crear una copia con flatten
datos = array.flatten()
print(datos)

[[2 4 6]
 [1 2 3]]
[2 4 6 1 2 3]
[[2 4]
 [6 1]
 [2 3]]
[2 4 6 1 2 3]
[2 4 6 1 2 3]


In [49]:
#Construir un array apartir de otros arrays existentes

a = np.random.randint(0,9,(2,4))
print(a)
b = np.random.randint(0,2,(2,2))
print(b)
c = np.random.randint(1,100,(2,2))
print(c)

#vstack -> concatena verticalmente
#hstack -> concatena horizontalmente

print(np.hstack((a,b)))
print(np.vstack((b,c)))




[[5 3 7 5]
 [6 3 3 2]]
[[0 1]
 [1 0]]
[[84 52]
 [39 44]]
[[5 3 7 5 0 1]
 [6 3 3 2 1 0]]
[[ 0  1]
 [ 1  0]
 [84 52]
 [39 44]]


In [ ]:
#podemos usar np.insert , np.append y np.delete
#devuelve una copia del array origin

